CREATE VIEW fReceiptTEST5 AS
WITH cte AS (
SELECT 
    r.receipt_id AS r_receipt_id, 
    r.terminalid AS r_terminalid, 
    r.warehouseid AS r_warehouseid, 
    r.users_id AS r_users_id, 
    r.dates AS r_dates, 
    r.marker AS r_marker, 
    r.corp_code AS r_corp_code, 
    r.fr_session AS r_fr_session, 
    r.doc_type AS r_doc_type, 
    r.doc_num AS r_doc_num, 
    r.doc_num_session AS r_doc_num_session, 
    r.discount AS r_discount, 
    r.discount_misc AS r_discount_misc, 
    r.amount AS r_amount, 
    r.round_amount AS r_round_amount, 
    r.pay_cash AS r_pay_cash, 
    r.pay_card AS r_pay_card, 
    r.pay_tare AS r_pay_tare, 
    r.pay_credit AS r_pay_credit, 
    r.pay_bonus_id AS r_pay_bonus_id, 
    r.pay_bonus_amount AS r_pay_bonus_amount, 
    r.pinpad_name AS r_pinpad_name, 
    r.terminal_number AS r_terminal_number, 
    r.short_fiscal_serial_number AS r_short_fiscal_serial_number, 
    r.device_model_name AS r_device_model_name, 
    r.device_model_version AS r_device_model_version, 
    r.terminal_description AS r_terminal_description, 
    r.is_electronic AS r_is_electronic, 
    r.fiscal_attribute AS r_fiscal_attribute, 
    r.vat10_sum AS r_vat10_sum, 
    r.vat18_sum AS r_vat18_sum, 
    r.vat20_sum AS r_vat20_sum, 
    r.items_count AS r_items_count,
    rl.line_id AS rl_line_id, 
    rl.itemid AS rl_itemid, 
    rl.quantity AS rl_quantity, 
    rl.pricebase AS rl_pricebase, 
    rl.pricesale AS rl_pricesale, 
    rl.discount AS rl_discount, 
    rl.amount AS rl_amount, 
    rl.barcode AS rl_barcode, 
    rl.cogs AS rl_cogs, 
    rl.users_id AS rl_users_id, 
    rl.vat_applied AS rl_vat_applied, 
    rl.vat_amount AS rl_vat_amount, 
    rl.onhand_id AS rl_onhand_id,
    COUNT(rl.line_id) OVER (PARTITION BY r.receipt_id) AS cnt_lines
FROM  
    [dbo].[fReceipts] r
LEFT JOIN 
    [dbo].[fReceiptsLines] rl
ON 
    r.receipt_id = rl.receipt_id
   
)

SELECT 
r_receipt_id,
r_terminalid,
r_warehouseid,
r_users_id,
r_dates,
r_marker,
r_corp_code,
r_fr_session,
r_doc_type,
r_doc_num,
r_doc_num_session,
CASE WHEN cnt_lines > 0 THEN r_discount / cnt_lines ELSE r_discount END AS r_discount,
CASE WHEN cnt_lines > 0 THEN r_discount_misc / cnt_lines ELSE r_discount_misc END AS r_discount_misc,
CASE WHEN cnt_lines > 0 THEN r_amount / cnt_lines ELSE r_amount END AS r_amount,
CASE WHEN cnt_lines > 0 THEN r_round_amount / cnt_lines ELSE r_round_amount END AS r_round_amount,
CASE WHEN cnt_lines > 0 THEN r_pay_cash / cnt_lines ELSE r_pay_cash END AS r_pay_cash,
CASE WHEN cnt_lines > 0 THEN r_pay_card / cnt_lines ELSE r_pay_card END AS r_pay_card,
CASE WHEN cnt_lines > 0 THEN r_pay_tare / cnt_lines ELSE r_pay_tare END AS r_pay_tare,
CASE WHEN cnt_lines > 0 THEN r_pay_credit / cnt_lines ELSE r_pay_credit END AS r_pay_credit,
r_pay_bonus_id,
CASE WHEN cnt_lines > 0 THEN r_pay_bonus_amount / cnt_lines ELSE r_pay_bonus_amount END AS r_pay_bonus_amount,
r_pinpad_name,
r_terminal_number,
r_short_fiscal_serial_number,
r_device_model_name,
r_device_model_version,
r_terminal_description,
r_is_electronic,
r_fiscal_attribute,
CASE WHEN cnt_lines > 0 THEN r_vat10_sum / cnt_lines ELSE r_vat10_sum END AS r_vat10_sum,
CASE WHEN cnt_lines > 0 THEN r_vat18_sum / cnt_lines ELSE r_vat18_sum END AS r_vat18_sum,
CASE WHEN cnt_lines > 0 THEN r_vat20_sum / cnt_lines ELSE r_vat20_sum END AS r_vat20_sum,
r_items_count,
rl_line_id,
rl_itemid,
rl_quantity,
rl_pricebase,
rl_pricesale,
rl_discount,
rl_amount,
rl_barcode,
rl_cogs,
rl_users_id,
rl_vat_applied,
rl_vat_amount,
rl_onhand_id,
1 AS СheckDoubles
FROM cte;